In [64]:
import pandas as pd

df = pd.read_csv('DataFrame.csv', sep=",", encoding='UTF-8')

In [65]:
df.head()

,도착 시군구 코드,자치구,정류장수,노선수,승차총승객수,하차총승객수,승차평균승객수,하차평균승객수,총 이동 시간,총 이동 인구,평균 이동 시간(분),이동인구(합),동,한식 일반 음식점업.1,커피전문점.1,기타주점업.1,남자,여자,계
0,11010,종로구,349,106,5468935,5205394,131.889620,125.534028,9356120,19385709.60,21.349599,44.235978,소계,5912,3613,1413,74018,79666,153684
1,11020,중구,178,103,3776675,3598932,121.020124,115.324511,9306020,19715322.61,21.012462,44.516072,소계,6414,3542,982,63869,67581,131450
2,11030,용산구,323,67,4189977,4086474,137.891694,134.485421,8514380,14707082.87,21.364786,36.903883,소계,2987,2076,1332,114571,121947,236518
3,11040,성동구,435,58,2807280,2746738,96.377369,94.298888,8887140,17449273.95,21.740324,42.685596,소계,2785,1859,621,141662,149947,291609
4,11050,광진구,269,41,2749448,2753411,118.352546,118.523137,8625540,17947278.99,22.474283,46.762548,소계,2861,1887,1577,169525,183585,353110

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   도착 시군구 코드     25 non-null     int64
 1   자치구           25 non-null     object
 2   정류장수          25 non-null     int64
 3   노선수           25 non-null     int64
 4   승차총승객수        25 non-null     int64
 5   하차총승객수        25 non-null     int64
 6   승차평균승객수       25 non-null     float64
 7   하차평균승객수       25 non-null     float64
 8   총 이동 시간       25 non-null     int64
 9   총 이동 인구       25 non-null     float64
 10  평균 이동 시간(분)   25 non-null     float64
 11  이동인구(합)       25 non-null     float64
 12  동             25 non-null     object
 13  한식 일반 음식점업.1  25 non-null     int64
 14  커피전문점.1       25 non-null     int64
 15  기타주점업.1       25 non-null     int64
 16  남자            25 non-null     int64
 17  여자            25 non-null     int64
 18  계             25 non-null     int64
dtypes: float64(5), int64(12), object(2)
memory usage: 3.8+ KB

## 목표

*  버스 노선 추가 필요 대상 지역(구 단위)을 선정
*  타겟 설정 ( 노선 수 )
*  승차 승객 수 와 하차 승객 수를 합쳐 승하차 총 승객수를 만들어줌

In [67]:
# 시각화 한글폰트 설정
import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='Malgun Gothic')
sns.set(font="Malgun Gothic",#"NanumGothicCoding", 
        rc={"axes.unicode_minus":False}, # 마이너스 부호 깨짐 현상 해결
        style='darkgrid')

In [68]:
# 원래는 상관계수 만이 절대적 지표는 아니지만 다른 신뢰성을 평가할만한 방법 x
corr = df.corr()
corr

,도착 시군구 코드,정류장수,노선수,승차총승객수,하차총승객수,승차평균승객수,하차평균승객수,총 이동 시간,총 이동 인구,평균 이동 시간(분),이동인구(합),한식 일반 음식점업.1,커피전문점.1,기타주점업.1,남자,여자,계
도착 시군구 코드,1.000000,0.447511,-0.069435,0.440756,0.441705,0.017980,0.029956,0.235541,0.473119,0.533514,0.610548,0.308156,0.267956,0.318339,0.697314,0.675779,0.687074
정류장수,0.447511,1.000000,0.258798,0.566681,0.578479,-0.135318,-0.099146,0.356947,0.355635,0.223747,0.374723,0.146445,0.209808,0.315121,0.550032,0.580536,0.566615
노선수,-0.069435,0.258798,1.000000,0.665488,0.652642,0.493541,0.470440,0.388332,0.226437,-0.678600,-0.003649,0.413556,0.425180,0.262016,-0.294351,-0.268906,-0.281536
승차총승객수,0.440756,0.566681,0.665488,1.000000,0.996610,0.538720,0.547384,0.581339,0.576553,-0.110113,0.474049,0.574076,0.530386,0.493852,0.359532,0.368034,0.364433
하차총승객수,0.441705,0.578479,0.652642,0.996610,1.000000,0.534826,0.555137,0.572769,0.558699,-0.097082,0.463898,0.538578,0.494266,0.485755,0.384499,0.390470,0.388119
승차평균승객수,0.017980,-0.135318,0.493541,0.538720,0.534826,1.000000,0.989288,0.140483,0.067920,-0.382202,-0.079733,0.257629,0.204745,0.220043,-0.255715,-0.282278,-0.269854
하차평균승객수,0.029956,-0.099146,0.470440,0.547384,0.555137,0.989288,1.000000,0.148381,0.062384,-0.356171,-0.072466,0.212645,0.160374,0.227213,-0.192074,-0.221558,-0.207643
총 이동 시간,0.235541,0.356947,0.388332,0.581339,0.572769,0.140483,0.148381,1.000000,0.923298,-0.141914,0.808313,0.816341,0.835772,0.655550,0.350985,0.393565,0.373570
총 이동 인구,0.473119,0.355635,0.226437,0.576553,0.558699,0.067920,0.062384,0.923298,1.000000,0.095727,0.951399,0.872074,0.873656,0.678119,0.509632,0.544162,0.528251
평균 이동 시간(분),0.533514,0.223747,-0.678600,-0.110113,-0.097082,-0.382202,-0.356171,-0.141914,0.095727,1.000000,0.373091,-0.128780,-0.181316,-0.034993,0.644669,0.631852,0.638885
이동인구(합),0.610548,0.374723,-0.003649,0.474049,0.463898,-0.079733,-0.072466,0.808313,0.951399,0.373091,1.000000,0.745931,0.736411,0.615303,0.681313,0.708455,0.696328
한식 일반 음식점업.1,0.308156,0.146445,0.413556,0.574076,0.538578,0.257629,0.212645,0.816341,0.872074,-0.128780,0.745931,1.000000,0.948958,0.651094,0.153125,0.174030,0.164188
커피전문점.1,0.267956,0.209808,0.425180,0.530386,0.494266,0.204745,0.160374,0.835772,0.873656,-0.181316,0.736411,0.948958,1.000000,0.760153,0.130900,0.168571,0.150638
기타주점업.1,0.318339,0.315121,0.262016,0.493852,0.485755,0.220043,0.227213,0.655550,0.678119,-0.034993,0.615303,0.651094,0.760153,1.000000,0.298162,0.328284,0.314207
남자,0.697314,0.550032,-0.294351,0.359532,0.384499,-0.255715,-0.192074,0.350985,0.509632,0.644669,0.681313,0.153125,0.130900,0.298162,1.000000,0.994596,0.998546
여자,0.675779,0.580536,-0.268906,0.368034,0.390470,-0.282278,-0.221558,0.393565,0.544162,0.631852,0.708455,0.174030,0.168571,0.328284,0.994596,1.000000,0.998747
계,0.687074,0.566615,-0.281536,0.364433,0.388119,-0.269854,-0.207643,0.373570,0.528251,0.638885,0.696328,0.164188,0.150638,0.314207,0.998546,0.998747,1.000000

* 값들 중 노선수 |corr| 값이 0.5 이상이 되는 것들을 선별

In [63]:
corr2 = corr.loc[abs(corr.노선수) >= 0.5]
corr2[['노선수']]

                  노선수
노선수          1.000000
승차총승객수       0.665488
하차총승객수       0.652642
평균 이동 시간(분) -0.678600
승하차총승객수      0.659671

* target값과 승차총승객수, 하차총 승객수, 평균이동시간이 관련있다고 판단
* 두 변수의 p-value 값도 비교해서 유의미성 판단

In [35]:
import scipy.stats as spst

In [36]:
print(spst.pearsonr(df.정류장수, df.승차총승객수))
print(spst.pearsonr(df.정류장수, df.하차총승객수))
print('-'*50)
print(spst.pearsonr(df.노선수, df.승차총승객수))
print(spst.pearsonr(df.노선수, df.하차총승객수))

PearsonRResult(statistic=0.5666813370974585, pvalue=0.003141977397117322)
PearsonRResult(statistic=0.5784790149467576, pvalue=0.0024518332034538645)
--------------------------------------------------
PearsonRResult(statistic=0.6654877832095702, pvalue=0.0002830862285771981)
PearsonRResult(statistic=0.6526422720355217, pvalue=0.00040610118937178525)

* p-value값도 모두 < 0.05 (귀무가설 기각, 대립가설 채택)
* 이로서 정류장수, 노선수 는 승차총승객수, 하차총승객수와 관련이 있다 채택
* target 값과 변수를 나누어 비율 산정

In [40]:
df['비율1'] = df['정류장수'] / df['승차총승객수'] * 10000
df.sort_values(by=['비율1']).head()

,도착 시군구 코드,자치구,정류장수,노선수,승차총승객수,하차총승객수,승차평균승객수,하차평균승객수,총 이동 시간,총 이동 인구,평균 이동 시간(분),이동인구(합),동,한식 일반 음식점업.1,커피전문점.1,기타주점업.1,남자,여자,계,비율1
1,11020,중구,178,103,3776675,3598932,121.020124,115.324511,9306020,19715322.61,21.012462,44.516072,소계,6414,3542,982,63869,67581,131450,0.471314
5,11060,동대문구,306,73,5240565,5115379,131.841430,128.692017,8838130,16288077.28,21.673451,39.942708,소계,3566,1472,1082,172318,180274,352592,0.583907
20,11210,관악구,466,86,7655819,7792476,154.753674,157.516040,8772170,18725641.04,23.377928,49.904036,소계,3689,2049,1672,250450,249886,500336,0.608687
22,11230,강남구,499,91,8030483,7569213,128.767927,121.371512,11437560,44684651.43,23.094565,90.226636,소계,11486,7273,2528,257096,280242,537338,0.621382
0,11010,종로구,349,106,5468935,5205394,131.889620,125.534028,9356120,19385709.60,21.349599,44.235978,소계,5912,3613,1413,74018,79666,153684,0.638150

In [41]:
df['비율2'] = df['정류장수'] / df['하차총승객수'] * 10000
df.sort_values(by=['비율1']).head()

,도착 시군구 코드,자치구,정류장수,노선수,승차총승객수,하차총승객수,승차평균승객수,하차평균승객수,총 이동 시간,총 이동 인구,...,이동인구(합),동,한식 일반 음식점업.1,커피전문점.1,기타주점업.1,남자,여자,계,비율1,비율2
1,11020,중구,178,103,3776675,3598932,121.020124,115.324511,9306020,19715322.61,...,44.516072,소계,6414,3542,982,63869,67581,131450,0.471314,0.494591
20,11210,관악구,466,86,7655819,7792476,154.753674,157.516040,8772170,18725641.04,...,49.904036,소계,3689,2049,1672,250450,249886,500336,0.608687,0.598013
5,11060,동대문구,306,73,5240565,5115379,131.841430,128.692017,8838130,16288077.28,...,39.942708,소계,3566,1472,1082,172318,180274,352592,0.583907,0.598196
22,11230,강남구,499,91,8030483,7569213,128.767927,121.371512,11437560,44684651.43,...,90.226636,소계,11486,7273,2528,257096,280242,537338,0.621382,0.659250
0,11010,종로구,349,106,5468935,5205394,131.889620,125.534028,9356120,19385709.60,...,44.235978,소계,5912,3613,1413,74018,79666,153684,0.638150,0.670458

In [42]:
df['비율3'] = df['노선수'] / df['승차총승객수'] * 10000
df.sort_values(by=['비율3']).head()

,도착 시군구 코드,자치구,정류장수,노선수,승차총승객수,하차총승객수,승차평균승객수,하차평균승객수,총 이동 시간,총 이동 인구,...,동,한식 일반 음식점업.1,커피전문점.1,기타주점업.1,남자,여자,계,비율1,비율2,비율3
24,11250,강동구,369,21,2890053,2830506,99.161194,97.118065,8430800,21101460.33,...,소계,3388,1660,1349,227891,237206,465097,1.276793,1.303654,0.072663
23,11240,송파구,415,55,5641742,5603488,114.270072,113.495260,10610520,34837613.05,...,소계,5760,3372,1469,321963,346298,668261,0.735588,0.740610,0.097488
15,11160,강서구,566,49,4681083,4652828,88.119480,87.587591,9388010,21839762.06,...,소계,4584,2530,1709,277797,300629,578426,1.209122,1.216464,0.104677
20,11210,관악구,466,86,7655819,7792476,154.753674,157.516040,8772170,18725641.04,...,소계,3689,2049,1672,250450,249886,500336,0.608687,0.598013,0.112333
22,11230,강남구,499,91,8030483,7569213,128.767927,121.371512,11437560,44684651.43,...,소계,11486,7273,2528,257096,280242,537338,0.621382,0.659250,0.113318

In [45]:
df['비율4'] = df['노선수'] / df['하차총승객수'] * 10000
df.sort_values(by=['비율4']).head()

,도착 시군구 코드,자치구,정류장수,노선수,승차총승객수,하차총승객수,승차평균승객수,하차평균승객수,총 이동 시간,총 이동 인구,...,한식 일반 음식점업.1,커피전문점.1,기타주점업.1,남자,여자,계,비율1,비율2,비율3,비율4
24,11250,강동구,369,21,2890053,2830506,99.161194,97.118065,8430800,21101460.33,...,3388,1660,1349,227891,237206,465097,1.276793,1.303654,0.072663,0.074192
23,11240,송파구,415,55,5641742,5603488,114.270072,113.495260,10610520,34837613.05,...,5760,3372,1469,321963,346298,668261,0.735588,0.740610,0.097488,0.098153
15,11160,강서구,566,49,4681083,4652828,88.119480,87.587591,9388010,21839762.06,...,4584,2530,1709,277797,300629,578426,1.209122,1.216464,0.104677,0.105312
20,11210,관악구,466,86,7655819,7792476,154.753674,157.516040,8772170,18725641.04,...,3689,2049,1672,250450,249886,500336,0.608687,0.598013,0.112333,0.110363
22,11230,강남구,499,91,8030483,7569213,128.767927,121.371512,11437560,44684651.43,...,11486,7273,2528,257096,280242,537338,0.621382,0.659250,0.113318,0.120224

* 비율 1 에서 '중구', '동대문구', '관악구', '강남', '종로' 가 1 ,2 ,3, 4, 5등
* 비율 2 에서 '중구', '관악구', '동대문구', '강남', '종로' 가 1, 2, 3, 4, 5등
* 비율 3 에서 '강동구', '송파구', '강서구', '관악구', '강남구' 가 1, 2, 3, 4, 5등
* 비율 4 에서 '강동구', '송파구', '강서구', '관악구', '강남구' 가 1, 2, 3, 4, 5등

- 따라서 비율 1등 중구, 강동구 / 비율4개가 모두 겹치는 관악구 선택